apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    nfsvolume/component: nfs-volume
  name: nfs1
  namespace: anonymous
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs"
